# Generated by Django 5.0.4 on 2024-04-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='inventory',
            field=models.IntegerField(default=10),
        ),
    ]
